-- AETH AN GRAEY order database setup
-- Apply this in Supabase to create and maintain the orders table used by the checkout flow.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  customer_name text not null,
  customer_email text not null,
  delivery_address text not null,
  phone_number text not null,
  shoe_size text not null,
  product_name text not null,
  product_handle text not null,
  amount_minor integer not null,
  currency text not null,
  order_status text not null default 'pending',
  payment_status text not null default 'pending',
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  paid_at timestamptz,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_status_check check (order_status in ('pending', 'confirmed', 'failed', 'cancelled')),
  constraint orders_payment_status_check check (payment_status in ('pending', 'paid', 'failed', 'cancelled'))
);

create index if not exists orders_payment_status_idx on public.orders (payment_status);
create index if not exists orders_customer_email_idx on public.orders (customer_email);
create index if not exists orders_order_id_idx on public.orders (order_id);
create index if not exists orders_stripe_checkout_session_id_idx on public.orders (stripe_checkout_session_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_set_updated_at on public.orders;

create trigger orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();
