create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  customer_name text not null,
  customer_email text not null,
  delivery_address text not null,
  phone_number text not null,
  shoe_size text not null,
  product_name text not null,
  product_handle text not null,
  amount_minor integer not null,
  currency text not null,
  status text not null default 'pending',
  payment_status text not null default 'pending',
  razorpay_order_id text,
  razorpay_payment_id text,
  razorpay_signature text,
  paid_at timestamptz,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_payment_status_idx on public.orders (payment_status);
create index if not exists orders_customer_email_idx on public.orders (customer_email);
